# Generated by Django 6.0.1 on 2026-01-27 23:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import marketing.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_phase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('product', 'Product Promotion'), ('segment', 'Segment Targeting'), ('schedule', 'Scheduling'), ('channel', 'Channel Optimization')], max_length=20)),
                ('payload', models.JSONField()),
                ('score', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('create_campaign', 'Create Campaign'), ('schedule_campaign', 'Schedule Campaign'), ('send_campaign', 'Send Campaign')], max_length=40)),
                ('config', models.JSONField(blank=True, default=marketing.models.empty_dict)),
                ('schedule_expression', models.CharField(default='@daily', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('settled', 'Settled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=marketing.models.empty_dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('channel_payload', models.JSONField()),
                ('status', models.CharField(choices=[('experimental', 'Experimental'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='experimental', max_length=20)),
                ('metrics', models.JSONField(default=marketing.models.default_variant_metrics)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('purchase', 'Purchase'), ('browse', 'Browsing Session'), ('cart', 'Cart Event'), ('email_open', 'Email Open'), ('click', 'Click-through'), ('whatsapp_reply', 'WhatsApp Reply')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=marketing.models.empty_dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='campaignmessage',
            new_name='marketing_c_campaig_ddb9ab_idx',
            old_name='marketing_campai_campaig_a6458f_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='optimization_metadata',
            field=models.JSONField(blank=True, default=marketing.models.empty_dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recommended_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='churn_predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='churn_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='interest_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_channels',
            field=models.JSONField(blank=True, default=marketing.models.empty_list),
        ),
        migrations.AddField(
            model_name='customer',
            name='recommended_products',
            field=models.JSONField(blank=True, default=marketing.models.empty_list),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Marketing Manager'), ('analyst', 'Analyst'), ('store', 'Store Owner'), ('agency', 'Agency')], default='manager', max_length=20),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignpayment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignvariant',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='marketing.campaignvariant'),
        ),
        migrations.AddField(
            model_name='customerevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketing.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignvariant',
            unique_together={('campaign', 'label')},
        ),
    ]
