"""URL routes for the marketing backend APIs."""
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    ActivityLogListView,
    AISuggestionActionView,
    AISuggestionListView,
    AutomationRuleDetailView,
    AutomationRuleListCreateView,
    AutomationRunView,
    CampaignDetailView,
    CampaignExportView,
    CampaignListCreateView,
    CampaignLogListView,
    CampaignMessageListView,
    CampaignPaymentCreateView,
    CampaignScheduleView,
    CampaignSendView,
    CampaignSuggestionDecisionView,
    CampaignSuggestionGenerateView,
    CampaignVariantListView,
    ChurnRiskView,
    ContentUpdateView,
    CustomerDetailView,
    CustomerEventIngestView,
    CustomerListCreateView,
    CustomerSegmentDetailView,
    CustomerSegmentListCreateView,
    CustomerUploadView,
    DashboardView,
    GenerateProductContentView,
    LoginView,
    NotificationListView,
    NotificationUpdateView,
    ProductContentListView,
    ProductListCreateView,
    RealtimeAnalyticsView,
    SignupView,
)

urlpatterns = [
    path('signup', SignupView.as_view(), name='signup'),
    path('login', LoginView.as_view(), name='login'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('products', ProductListCreateView.as_view(), name='products'),
    path(
        'products/<uuid:product_id>/generate_content',
        GenerateProductContentView.as_view(),
        name='generate_content',
    ),
    path(
        'products/<uuid:product_id>/content',
        ProductContentListView.as_view(),
        name='product_content',
    ),
    path(
        'products/<uuid:product_id>/content/<uuid:content_id>',
        ContentUpdateView.as_view(),
        name='content_update',
    ),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('logs', ActivityLogListView.as_view(), name='logs'),
    path('customers', CustomerListCreateView.as_view(), name='customers'),
    path('customers/upload', CustomerUploadView.as_view(), name='customer_upload'),
    path('customers/<uuid:pk>', CustomerDetailView.as_view(), name='customer_detail'),
    path('customers/<uuid:customer_id>/events', CustomerEventIngestView.as_view(), name='customer_events'),
    path('segments', CustomerSegmentListCreateView.as_view(), name='segments'),
    path('segments/<uuid:pk>', CustomerSegmentDetailView.as_view(), name='segment_detail'),
    path('automation/rules', AutomationRuleListCreateView.as_view(), name='automation_rules'),
    path('automation/rules/<uuid:pk>', AutomationRuleDetailView.as_view(), name='automation_rule_detail'),
    path('automation/run', AutomationRunView.as_view(), name='automation_run'),
    path('campaigns', CampaignListCreateView.as_view(), name='campaigns'),
    path('campaigns/export', CampaignExportView.as_view(), name='campaign_export'),
    path('campaigns/<uuid:pk>', CampaignDetailView.as_view(), name='campaign_detail'),
    path('campaigns/<uuid:campaign_id>/suggestions', CampaignSuggestionGenerateView.as_view(), name='campaign_suggestions'),
    path(
        'campaigns/<uuid:campaign_id>/suggestions/<uuid:suggestion_id>',
        CampaignSuggestionDecisionView.as_view(),
        name='campaign_suggestion_decision',
    ),
    path('campaigns/<uuid:campaign_id>/schedule', CampaignScheduleView.as_view(), name='campaign_schedule'),
    path('campaigns/<uuid:campaign_id>/send', CampaignSendView.as_view(), name='campaign_send'),
    path('campaigns/<uuid:campaign_id>/payments', CampaignPaymentCreateView.as_view(), name='campaign_payments'),
    path('campaigns/<uuid:campaign_id>/messages', CampaignMessageListView.as_view(), name='campaign_messages'),
    path('campaigns/<uuid:campaign_id>/logs', CampaignLogListView.as_view(), name='campaign_logs'),
    path('campaigns/<uuid:campaign_id>/variants', CampaignVariantListView.as_view(), name='campaign_variants'),
    path('analytics/realtime', RealtimeAnalyticsView.as_view(), name='analytics_realtime'),
    path('analytics/churn', ChurnRiskView.as_view(), name='analytics_churn'),
    path('ai/suggestions', AISuggestionListView.as_view(), name='ai_suggestions'),
    path('ai/suggestions/<uuid:suggestion_id>/action', AISuggestionActionView.as_view(), name='ai_suggestion_action'),
    path('notifications', NotificationListView.as_view(), name='notifications'),
    path('notifications/<uuid:notification_id>/read', NotificationUpdateView.as_view(), name='notification_read'),
]
